---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(tidytext)
library(janeaustenr)
```

Find the most common words in both Pride & Prejudice and Sense & Sensibility.

```{r}
pride_p <- tibble(
  sentence = 1:length(prideprejudice), 
  text = prideprejudice
) %>% 
  unnest_tokens(word, text) 

pride_p %>%
  count(word, sort = TRUE)
```


```{r}
sense_s <- tibble(
  sentence = 1:length(sensesensibility),
  text = sensesensibility
) %>% 
  unnest_tokens(word, text)

sense_s %>%
  count(word, sort = TRUE)
```

ind the most common words in both Pride & Prejudice and Sense & Sensibility, not including stop words

```{r}
pride_p %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)

```

```{r}
sense_s %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)
```

Find the most common sentiment words in both Pride & Prejudice and Sense & Sensibility.

```{r}
library(textdata)
```

```{r}
  pride_p_sentiment <- pride_p %>%
  inner_join(get_sentiments("afinn")) %>%
  arrange(desc(value))
```

```{r}
sense_s_sentiment <- sense_s %>%
inner_join(get_sentiments("afinn")) %>%
arrange(desc(value))

```

