---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(dplyr)
library(cluster)
library(factoextra)
library(dendextend)
```



```{r}
computers <- read_csv("data/computers.csv")
```

```{r}
#This data does look potentially good for clustering but will need more investigation
head(computers)
```

```{r}
dim(computers)
```

```{r}
class(computers)
```

```{r}
any(is.na(computers))
```

```{r}
#standardising the data

computers1 <- computers %>%
  clean_names()
```

```{r}
computers1 <- computers %>%
    select(hd, ram)

head(computers1)
```

```{r}
ggplot(computers1, aes(hd, ram)) +
  geom_point()
```


```{r}
summary(computers1)
```
```{r}

computers1_scale <- computers1 %>%
                    mutate_all(scale)
 
computers1_scale
```

```{r}
library(broom)

clustered_computers <- kmeans(computers1_scale, centers = 6, nstart = 25)
```


```{r}
tidy(clustered_computers, 
     col.names = colnames(computers1_scale))
```

```{r}
glance(clustered_computers)

```

```{r}
augment(clustered_computers, computers1)
```

```{r}
library(animation)

computers1_scale %>% 
  kmeans.ani(centers = 6) 
```


```{r}
glance(clustered_computers)
```

```{r}
max_k <- 20 

k_clusters <- tibble(k = 1:max_k) %>%
  mutate(
    kclust = map(k, ~ kmeans(computers1_scale, .x, nstart = 25)), 
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, computers1)
  )

k_clusters
```

```{r}
library(factoextra)
```

```{r}
fviz_nbclust(computers1_scale, kmeans, method = "wss", nstart = 25)
```

```{r}
fviz_nbclust(computers1_scale, kmeans, method = "silhouette", nstart = 25)
```


```{r}
fviz_nbclust(computers1_scale, kmeans, method = "gap_stat", nstart = 25, k.max = 10)
```


```{r}
 clusterings %>% 
  unnest(cols = c(augmented)) %>%
  filter(k <= 6) %>%
 ggplot(aes(x = hd, y = ram)) +
  geom_point(aes(color = .cluster)) + 
  facet_wrap(~ k)
```


```{r}
clusterings %>% 
  unnest(augmented) %>%
  filter(k == 2) %>%
  group_by(.cluster) %>%
  summarise(mean(hd), mean(ram))
```

