---
title: "R Notebook"
output: html_notebook
---

code to install and load dataset packages

```{r}
install.packages("devtools")
```

```{r}
devtools::install_github('codeclan/CodeClanData')

```

```{r}
library(CodeClanData)
```

```{r}
beer
```


```{r}
class(beer)
```

```{r}
str(beer)
```

what are the mean values of all the numeric variables
```{r}
beer[ ,3:5]
#this shows the last 3 columns.
```


```{r}
max(beer[ ,3])

#maximum of percentage column
```

```{r}
min(beer[ ,3])

#minimum of percentage column
```

```{r}
mean(beer[ ,3])
#average percentage
```

```{r}
mean(beer[ ,5])
#avenage carb
```

```{r}
temp_data_b$brand
#this is all the bramds showing
```

```{r}
temp_data_b[ , 1:2]
```

```{r}
temp_data_b[ ,-4]
#everything except the calories
```

```{r}
temp_data_b[ 3 < 6]
```


```{r}
sum(temp_data_t)
#adds up all elements 
```

```{r}
mean(temp_data_t)

#average of temp
```

```{r}
str(temp_data_t)
```



```{r}
game_of_thrones
```



```{r}
temp_data_b <- CodeClanData::beer
```


```{r}
temp_data_t <- CodeClanData::temp
```

```{r}
str(temp_data)
#this shows the structure of the gane of thrones package
```

```{r}
str(temp_data_b)
#this shows the structure of the beed df
```

```{r}
str(temp_data_t)
#the structre of the temperature dataset
```

